### PR TITLE
tacd: update dependencies via cargo update

### PR DESCRIPTION
**Pull request by hnez**
A routine update inspired by #80. It does not get rid of the security advisory though.

### CODE REVIEW

**Comment by Emantor** [comment]
We gain `windows-sys` which according to the [crate information](https://crates.io/crates/windows-sys) is used for Windows APIs. We don't have those, so I suspect this can be disabled through explicit feature specification.

**Comment by hnez** [comment]
> We gain `windows-sys` …

*yet another version of windows-sys:

https://github.com/linux-automation/tacd/blob/b245e39c9f8283461340abca2afcfa7e8d687792/Cargo.lock#L3151-L3176

As far as I can tell the `Cargo.lock` lists the hashes of any package that *may* be used in any possible build scenario.
I do not know if feature flags set in the `Cargo.toml`affect it that much.

I think most important for us is that none of the `windows-sys` versions listed in the `Cargo.lock` are actually compiled when the `tacd` is built.

**Comment by Emantor** [comment]
Ah, TIL. Apparently `Cargo.lock` always contains all build deps so it stays consistent across platforms which makes sense to me.

**Comment by hnez** [comment]
Hi @Emantor, now that the `windows-sys` questions are resolved, could you give this an approval?
I already have the next set of updates in the pipeline with #84.

**Comment by hnez** [comment]
I was about to just merge this myself, but it turns out I do not have permissions to do that.
Soo @KarlK90 or @Emantor, can I get an approval please?

**Review by KarlK90 — APPROVED** [review]

**Pull request merged**
