### PR TITLE
web: fixes to make the CI work and general maintainance

### PR DESCRIPTION
**Pull request by hnez**
Hi,

some maintainance on the web interface to make the CI jobs happy and to make sure that the project works with updated dependencies.

There is also a cosmetic change to the buttons that control the view of the LCD/OLED on the device:

* before:
  before
* after:
  after

### CODE REVIEW

**Comment by hnez** [comment]
I have re-worked the PR. The `MqttDurationButton` is now gone completely.
Long and short presses in a web interface felt weird anyways.
We now have two separate (web interface) buttons per hardware button (see the updated image in the PR description).
I've also gone ahead and swapped the "Upper" and "Lower" button so they match the new layout of the TAC (mainboard on top, powerboard at the bottom).

**Comment by Emantor** [comment]
Now that the duration is no longer used within JS, we can probably remove the duration parameter on the button endpoint and rename it to `long_press` or something similar.

**Comment by hnez** [comment]
You  are right. I will have a look at the daemon side of the API if implementing it e.g. with a `enum { ShortPress, LongPress}` would make the implementation unnecessarily clunky.
If not I will implement it that way.
I've also noticed that the endpoint is not documented in the `openapi.yaml`, which I will also change for completeness sake.

**Comment by hnez** [comment]
These changes are included in the mega cleanup PR #16.

**Pull request closed without merging**
